packages:
  - viewer/dev-binary-core
  - viewer/i18n
  - viewer/protocol
  - viewer/rendering
  - viewer/rendering-3d
  - viewer/runtime-assets
  - viewer/raw-decoder
  - viewer/testing
  - viewer/ui
  - viewer/plugins/*
