import type { PanoramaViewerContent } from "./types";

export const panoramaViewerContents: readonly PanoramaViewerContent[] = [
  {
    viewerId: "insta360",
    pluginId: "insta360",
    status: "published",
    formatExtensions: ["insv", "insp", "lrv", "dng"],
    copy: {
      en: {
        name: "Insta360",
        eyebrow: "INSTA360 ORIGINAL MEDIA VIEWER",
        title: "Open Insta360 files online without uploading",
        description: "View supported INSV, INSP, LRV and DNG originals from Insta360 cameras in an interactive 360° browser viewer.",
        introduction: "Skip the import queue when you only need to check a shot. Anyfile validates supported Insta360 layouts, decodes the selected media on this device and maps both lenses into an interactive panorama. Your original file is never sent to an Anyfile server.",
        openLabel: "Open an Insta360 file",
        models: ["Insta360 X3", "Insta360 ONE RS", "Insta360 X4", "Insta360 X5", "Insta360 X6"],
        formats: [
          { extension: "insv", label: "Original 360° video", description: "Paired X3/ONE RS recordings and verified single-file dual-track X4, X5 and X6 layouts." },
          { extension: "insp", label: "Panorama photo", description: "Verified X3 side-by-side dual-fisheye photos stored in a JPEG-based container." },
          { extension: "lrv", label: "Low-resolution proxy", description: "Verified X3 and X4 H.264/AAC proxies for quick interactive review." },
          { extension: "dng", label: "RAW panorama", description: "Verified X3 and X6 RAW layouts with local development and interactive viewing." },
        ],
        highlights: ["Interactive drag, keyboard and wheel navigation", "Local image, video and RAW decoding", "Original audio with playback and seeking where supported"],
        openingSteps: ["Keep matching _00 and _10 INSV files together for X3 and ONE RS recordings.", "Choose both matching files at once, or open their folder. X4, X5 and X6 dual-track INSV recordings open from one file.", "Anyfile checks the model and layout before loading the panorama viewer."],
        requirements: ["WebGL is required for interactive viewing.", "Video playback depends on browser support for the recording's H.264 or HEVC video and AAC audio.", "Modern INSV can fall back to an embedded static 360° preview when HEVC playback is unavailable."],
        limitations: ["Only the models and layouts listed on this page are declared as supported.", "HDR merging, gyro leveling and FlowState stabilization are not applied.", "This viewer does not edit, reframe or export footage."],
        faq: [
          { question: "Can I view an INSV file without Insta360 Studio?", answer: "Yes, when its model, layout and browser codecs are supported. The file is read and rendered locally by Anyfile." },
          { question: "Why does my Insta360 video have two INSV files?", answer: "X3 and ONE RS recordings can store one fisheye lens in each matching _00 and _10 file. Select both files or open their folder." },
          { question: "Are Insta360 files uploaded for viewing?", answer: "No. Validation, decoding and panorama rendering happen on this device." },
        ],
      },
      "zh-CN": {
        name: "Insta360",
        eyebrow: "INSTA360 原始素材查看器",
        title: "无需上传，在线打开 Insta360 文件",
        description: "在浏览器中把受支持的 INSV、INSP、LRV 与 DNG 原片作为交互式 360° 全景查看。",
        introduction: "只想检查拍摄内容时，无需等待导入。Anyfile 会校验受支持的 Insta360 布局，在当前设备解码所选素材，并把两路镜头映射成交互式全景。原始文件不会发送到 Anyfile 服务器。",
        openLabel: "打开 Insta360 文件",
        models: ["Insta360 X3", "Insta360 ONE RS", "Insta360 X4", "Insta360 X5", "Insta360 X6"],
        formats: [
          { extension: "insv", label: "原始全景视频", description: "支持 X3/ONE RS 配对录像，以及已验证的 X4、X5、X6 单文件双轨布局。" },
          { extension: "insp", label: "全景照片", description: "已验证的 X3 左右双鱼眼照片，使用基于 JPEG 的容器。" },
          { extension: "lrv", label: "低分辨率代理", description: "已验证的 X3、X4 H.264/AAC 代理文件，适合快速交互预览。" },
          { extension: "dng", label: "RAW 全景", description: "已验证的 X3、X6 RAW 布局，可在本地显影并交互查看。" },
        ],
        highlights: ["支持拖动、键盘与滚轮环视", "在本地完成图片、视频与 RAW 解码", "受支持时保留原始音频、播放与定位"],
        openingSteps: ["X3 与 ONE RS 录像请保留匹配的 _00、_10 INSV 文件。", "同时选择两个匹配文件，或打开它们所在的文件夹；X4、X5、X6 双轨 INSV 可直接选择单个文件。", "Anyfile 会先校验型号与文件布局，再加载全景查看器。"],
        requirements: ["交互查看需要 WebGL。", "视频播放取决于浏览器是否支持录像中的 H.264 或 HEVC 视频及 AAC 音频。", "无法播放 HEVC 时，新版 INSV 可以降级显示内嵌的静态 360° 预览。"],
        limitations: ["只声明本页列出的型号与文件布局。", "不应用 HDR 合成、陀螺仪水平校正与 FlowState 防抖。", "不提供剪辑、重新取景或导出。"],
        faq: [
          { question: "不用 Insta360 Studio 可以查看 INSV 吗？", answer: "可以，前提是文件型号、布局和浏览器 codec 均受支持；Anyfile 会在本地读取和渲染文件。" },
          { question: "为什么一段 Insta360 视频有两个 INSV 文件？", answer: "X3 与 ONE RS 可能把两路鱼眼分别保存在匹配的 _00、_10 文件中，请同时选择两个文件或打开所在文件夹。" },
          { question: "查看 Insta360 文件时会上传吗？", answer: "不会。校验、解码与全景渲染全部在当前设备完成。" },
        ],
      },
    },
  },
  {
    viewerId: "gopro-max",
    pluginId: "gopro-max",
    status: "published",
    formatExtensions: ["360", "jpg"],
    copy: {
      en: {
        name: "GoPro MAX",
        eyebrow: "GOPRO MAX ORIGINAL MEDIA VIEWER",
        title: "Play GoPro MAX .360 files online",
        description: "Open supported GoPro MAX and MAX2 camera-original .360 video without first exporting it to MP4.",
        introduction: "GoPro .360 originals contain two HEVC EAC tracks rather than a ready-made equirectangular video. Anyfile reads both tracks by byte range, decodes them on this device and maps their six faces into an interactive WebGL panorama without uploading the recording.",
        openLabel: "Open a GoPro MAX file",
        models: ["GoPro MAX", "GoPro MAX2"],
        formats: [
          { extension: "360", label: "Original 360° video", description: "Verified GoPro MAX 4096×1344 and MAX2 5952×1920 dual-track HEVC EAC layouts." },
          { extension: "jpg", label: "Panorama photo", description: "Verified 5760×2880 GoPro MAX equirectangular JPEG panoramas." },
        ],
        highlights: ["Direct viewing of camera-original .360 files", "Interactive EAC-to-panorama projection in WebGL", "AAC stereo playback, seeking, volume and view controls"],
        openingSteps: ["Choose the original .360 recording or a verified GoPro MAX panorama JPEG.", "Anyfile validates GoPro metadata and the expected media-track layout.", "The supported tracks are decoded and rendered locally as an interactive panorama."],
        requirements: ["Original .360 playback requires WebGL and WebCodecs.", "The browser and operating system must expose HEVC decoding.", "AAC playback uses local Web Audio capabilities."],
        limitations: ["Only verified MAX and MAX2 track layouts are declared.", "Ambisonic PCM, gyro leveling and stabilization metadata are not applied.", "This viewer does not reframe, edit or export footage."],
        faq: [
          { question: "Is a GoPro .360 file the same as an exported MP4?", answer: "No. The original contains two HEVC EAC tracks. Anyfile combines them for viewing without creating an exported MP4." },
          { question: "Do I need GoPro Player just to check a .360 recording?", answer: "Not when the file layout and your browser's HEVC decoder are supported by Anyfile." },
          { question: "Does Anyfile upload GoPro MAX footage?", answer: "No. Range reads, decoding, audio and WebGL rendering stay on this device." },
        ],
      },
      "zh-CN": {
        name: "GoPro MAX",
        eyebrow: "GOPRO MAX 原始素材查看器",
        title: "在线播放 GoPro MAX .360 原片",
        description: "无需先导出为 MP4，直接打开受支持的 GoPro MAX 与 MAX2 相机原始 .360 视频。",
        introduction: "GoPro .360 原片包含两条 HEVC EAC 轨道，并不是已经拼好的等距柱状视频。Anyfile 会分段读取两条轨道，在当前设备解码，并通过 WebGL 把六个画面映射成交互式全景，全程不上传录像。",
        openLabel: "打开 GoPro MAX 文件",
        models: ["GoPro MAX", "GoPro MAX2"],
        formats: [
          { extension: "360", label: "原始全景视频", description: "已验证 GoPro MAX 4096×1344 与 MAX2 5952×1920 双轨 HEVC EAC 布局。" },
          { extension: "jpg", label: "全景照片", description: "已验证的 5760×2880 GoPro MAX 等距柱状 JPEG 全景。" },
        ],
        highlights: ["直接查看相机原始 .360 文件", "通过 WebGL 交互映射 EAC 全景", "支持 AAC 立体声、播放、定位、音量与视角控制"],
        openingSteps: ["选择原始 .360 录像或已验证的 GoPro MAX 全景 JPEG。", "Anyfile 会校验 GoPro 元数据和预期的媒体轨道布局。", "受支持的轨道会在本地解码并渲染为可交互全景。"],
        requirements: ["原始 .360 播放需要 WebGL 与 WebCodecs。", "浏览器和操作系统必须提供 HEVC 解码能力。", "AAC 播放使用当前设备的 Web Audio 能力。"],
        limitations: ["只声明已验证的 MAX 与 MAX2 轨道布局。", "不应用 Ambisonic PCM、陀螺仪水平校正或防抖元数据。", "不提供重新取景、剪辑或导出。"],
        faq: [
          { question: "GoPro .360 文件和导出的 MP4 一样吗？", answer: "不一样。原始文件包含两条 HEVC EAC 轨道；Anyfile 会将它们组合显示，但不会生成导出的 MP4。" },
          { question: "只想检查 .360 录像也必须安装 GoPro Player 吗？", answer: "不必；当文件布局和浏览器 HEVC 解码能力受 Anyfile 支持时，可以直接查看。" },
          { question: "Anyfile 会上传 GoPro MAX 素材吗？", answer: "不会。分段读取、解码、音频与 WebGL 渲染都留在当前设备。" },
        ],
      },
    },
  },
  {
    viewerId: "dji-osmo-360",
    pluginId: "dji-osmo",
    status: "published",
    formatExtensions: ["osv", "jpg"],
    copy: {
      en: {
        name: "DJI Osmo 360",
        eyebrow: "DJI OSMO 360 ORIGINAL MEDIA VIEWER",
        title: "Open DJI Osmo 360 OSV files online",
        description: "Play verified DJI Osmo 360 OSV originals as interactive panoramas without uploading or converting them first.",
        introduction: "DJI Osmo 360 OSV recordings contain two square HEVC Main 10 lens tracks, audio and private camera metadata. Anyfile reads the large original by byte range, decodes both lenses locally and applies measured lens-specific calibration in WebGL.",
        openLabel: "Open a DJI Osmo 360 file",
        models: ["DJI Osmo 360 (verified OQ001 layout)"],
        formats: [
          { extension: "osv", label: "Original 360° video", description: "Verified dual 3840×3840 HEVC Main 10 lens tracks with AAC stereo audio." },
          { extension: "jpg", label: "Panorama photo", description: "Verified DJI OQ001 equirectangular JPEG panoramas." },
        ],
        highlights: ["Direct local viewing of camera-original OSV", "Measured focal, optical-center and rotation calibration per lens", "AAC stereo playback, seeking, volume and view controls"],
        openingSteps: ["Choose the original OSV recording or a verified Osmo 360 panorama JPEG.", "Anyfile checks DJI camera metadata and the dual-track layout.", "Both lens tracks are decoded locally and rendered as one interactive view."],
        requirements: ["OSV playback requires WebGL and WebCodecs.", "The browser and operating system must expose HEVC Main 10 decoding.", "Large 8K-class originals require sufficient graphics and decoder resources."],
        limitations: ["Only the verified OQ001 layout is declared.", "Gyro stabilization, HDR-accurate output and DJI private metadata are not applied.", "This viewer does not edit, reframe or export footage."],
        faq: [
          { question: "Can I view an OSV file without exporting it from DJI Studio?", answer: "Yes, when it matches the verified Osmo 360 layout and the browser provides HEVC Main 10 decoding." },
          { question: "Why will an OSV file not play in an ordinary video player?", answer: "An OSV original contains two separate lens tracks that need camera-specific projection before they look like a normal 360° panorama." },
          { question: "Is my DJI footage uploaded?", answer: "No. The original is read by byte range and decoded on this device." },
        ],
      },
      "zh-CN": {
        name: "DJI Osmo 360",
        eyebrow: "DJI OSMO 360 原始素材查看器",
        title: "在线打开 DJI Osmo 360 OSV 原片",
        description: "无需上传或预先转换，直接把已验证的 DJI Osmo 360 OSV 原片作为交互式全景播放。",
        introduction: "DJI Osmo 360 OSV 录像包含两条方形 HEVC Main 10 镜头轨、音频与相机私有元数据。Anyfile 会对大型原片进行分段读取，在本地解码两路镜头，并通过 WebGL 应用逐镜头实测标定。",
        openLabel: "打开 DJI Osmo 360 文件",
        models: ["DJI Osmo 360（已验证 OQ001 布局）"],
        formats: [
          { extension: "osv", label: "原始全景视频", description: "已验证双 3840×3840 HEVC Main 10 镜头轨与 AAC 立体声音频。" },
          { extension: "jpg", label: "全景照片", description: "已验证的 DJI OQ001 等距柱状 JPEG 全景。" },
        ],
        highlights: ["直接在本地查看相机原始 OSV", "应用实测的逐镜头焦距、光心与旋转标定", "支持 AAC 立体声、播放、定位、音量与视角控制"],
        openingSteps: ["选择原始 OSV 录像或已验证的 Osmo 360 全景 JPEG。", "Anyfile 会检查 DJI 相机元数据与双轨布局。", "两路镜头轨在本地解码，并渲染为一个可交互视图。"],
        requirements: ["OSV 播放需要 WebGL 与 WebCodecs。", "浏览器和操作系统必须提供 HEVC Main 10 解码能力。", "8K 级大型原片需要足够的图形与解码资源。"],
        limitations: ["只声明已验证的 OQ001 布局。", "不应用陀螺仪防抖、HDR 精确输出与 DJI 私有元数据。", "不提供剪辑、重新取景或导出。"],
        faq: [
          { question: "不从 DJI Studio 导出，可以直接查看 OSV 吗？", answer: "可以，前提是文件匹配已验证的 Osmo 360 布局，且浏览器提供 HEVC Main 10 解码。" },
          { question: "为什么普通播放器不能正常播放 OSV？", answer: "OSV 原片包含两条独立镜头轨，需要经过相机专用投影才能呈现为正常的 360° 全景。" },
          { question: "DJI 素材会被上传吗？", answer: "不会。原片会被分段读取，并在当前设备完成解码。" },
        ],
      },
    },
  },
];
