import type { Localized, PluginContent, PluginCopy, UpstreamProject } from "./types";

const upstream = (name: string, version: string, projectUrl: string, license: string, en: string, zh: string, noticeUrl?: string): UpstreamProject => ({
  name, version, projectUrl, license, noticeUrl, usage: { en, "zh-CN": zh },
});

const plugin = (
  pluginId: string,
  title: Localized<string>,
  description: Localized<string>,
  summary: Localized<string>,
  architecture: Localized<readonly string[]>,
  limitations: Localized<readonly string[]>,
  upstreamProjects: readonly UpstreamProject[] = [],
): PluginContent => ({
  pluginId, status: "published", upstreamProjects,
  copy: Object.fromEntries((["en", "zh-CN"] as const).map((locale) => [locale, {
    title: title[locale], description: description[locale], summary: summary[locale],
    architecture: architecture[locale], limitations: limitations[locale],
  }])) as Localized<PluginCopy>,
});

export const pluginContents: readonly PluginContent[] = [
  plugin("browser-video", { en: "How Anyfile's Browser Video Viewer Works", "zh-CN": "Anyfile 浏览器视频查看器如何工作" }, { en: "Track probing and local playback for browser-supported video.", "zh-CN": "探测轨道并在本地播放浏览器支持的视频。" }, { en: "This viewer inspects ISO BMFF or WebM tracks before handing verified codec combinations to the native media element.", "zh-CN": "该查看器先检查 ISO BMFF 或 WebM 轨道，再把已验证 codec 组合交给浏览器原生媒体元素。" }, { en: ["A lightweight probe reads container track metadata.", "The complete viewer creates an object URL and native video controls."], "zh-CN": ["轻量 probe 读取容器轨道元数据。", "完整查看器创建对象 URL 并使用原生视频控件。"] }, { en: ["Playable codecs vary by browser and operating system.", "Encrypted media is not supported."], "zh-CN": ["可播放 codec 随浏览器和操作系统变化。", "不支持加密媒体。"] }),
  plugin("non-native-video", { en: "How Anyfile's Matroska and Ogg Video Viewer Works", "zh-CN": "Anyfile Matroska 与 Ogg 视频查看器如何工作" }, { en: "Local demuxing and WebCodecs playback for selected non-native containers.", "zh-CN": "为部分非原生容器提供本地解封装与 WebCodecs 播放。" }, { en: "The viewer demuxes supported Matroska, transport-stream, QuickTime and Ogg files, then coordinates decoded video and audio on the device.", "zh-CN": "查看器在设备端解封装受支持的 Matroska、传输流、QuickTime 与 Ogg 文件，并协调解码后的音视频。" }, { en: ["Mediabunny parses supported containers and feeds WebCodecs.", "Ogg Theora uses a separately loaded OGV Worker/WASM path."], "zh-CN": ["Mediabunny 解析受支持容器并向 WebCodecs 供给数据。", "Ogg Theora 使用单独加载的 OGV Worker/WASM 路径。"] }, { en: ["Only documented codec and primary-track combinations are supported.", "Subtitles and complete multi-track controls are not available."], "zh-CN": ["只支持文档列明的 codec 与主轨组合。", "不提供字幕与完整多轨控制。"] }, [upstream("Mediabunny", "1.55.3", "https://github.com/Vanilagy/mediabunny", "MPL-2.0", "Container demuxing and media sample extraction.", "容器解封装与媒体采样提取。", "/vendor/licenses/mediabunny/1.55.3/MPL-2.0.txt"), upstream("OGV.js", "1.9.0", "https://github.com/brion/ogv.js", "MIT", "Worker/WASM decoding for Ogg Theora playback.", "用于 Ogg Theora 播放的 Worker/WASM 解码。")]),
  plugin("browser-audio", { en: "How Anyfile's Browser Audio Viewer Works", "zh-CN": "Anyfile 浏览器音频查看器如何工作" }, { en: "Local probing and native playback for common audio formats.", "zh-CN": "为常见音频提供本地探测与原生播放。" }, { en: "The audio viewer validates supported stream or container details and uses the browser media pipeline for playback.", "zh-CN": "音频查看器校验受支持的音频流或容器信息，并使用浏览器媒体管线播放。" }, { en: ["Format-specific probes reject unsupported variants.", "A native audio element provides playback, seeking and volume."], "zh-CN": ["格式专用 probe 会拒绝不支持的变体。", "原生 audio 元素提供播放、定位与音量。"] }, { en: ["Codec availability remains browser-dependent.", "The viewer does not edit audio or tags."], "zh-CN": ["codec 可用性仍取决于浏览器。", "查看器不编辑音频或标签。"] }),
  plugin("non-native-audio", { en: "How Anyfile's Matroska Audio Viewer Works", "zh-CN": "Anyfile Matroska 音频查看器如何工作" }, { en: "Local Matroska audio demuxing with WebCodecs and Web Audio.", "zh-CN": "通过 WebCodecs 与 Web Audio 在本地解封装 Matroska 音频。" }, { en: "This viewer selects one supported primary MKA track, decodes it locally and schedules samples through Web Audio.", "zh-CN": "该查看器选择一条受支持的 MKA 主音轨，在本地解码并通过 Web Audio 调度采样。" }, { en: ["Mediabunny reads Matroska track and sample data.", "Decoded samples are scheduled against a local playback clock."], "zh-CN": ["Mediabunny 读取 Matroska 轨道与采样数据。", "解码后的采样按本地播放时钟调度。"] }, { en: ["Only one primary track is used.", "Unsupported codecs and layouts are rejected by the probe."], "zh-CN": ["只使用一条主音轨。", "probe 会拒绝不支持的 codec 和布局。"] }, [upstream("Mediabunny", "1.55.3", "https://github.com/Vanilagy/mediabunny", "MPL-2.0", "Matroska demuxing and sample extraction.", "Matroska 解封装与采样提取。", "/vendor/licenses/mediabunny/1.55.3/MPL-2.0.txt")]),
  plugin("browser-image", { en: "How Anyfile's Browser Image Viewer Works", "zh-CN": "Anyfile 浏览器图片查看器如何工作" }, { en: "Safe local display for formats decoded natively by the browser.", "zh-CN": "安全地本地展示浏览器原生解码的图片格式。" }, { en: "The viewer validates that the selected file can be decoded, creates a temporary object URL and fits the image into the shared viewport.", "zh-CN": "查看器先验证所选文件可解码，再创建临时对象 URL，并将图片适配到共享视口。" }, { en: ["A probe performs a real image decode before selection.", "The rendering layer manages fit, zoom and resource cleanup."], "zh-CN": ["probe 在选择前执行真实图片解码。", "渲染层管理适配、缩放与资源释放。"] }, { en: ["Supported formats follow current browser decoders.", "Format-specific metadata is not exhaustively exposed."], "zh-CN": ["支持格式取决于当前浏览器解码器。", "不会穷尽展示格式专用元数据。"] }),
  plugin("modern-raster", { en: "How Anyfile's Modern Image Viewer Works", "zh-CN": "Anyfile 现代图片查看器如何工作" }, { en: "Native-first JPEG XL and HEIF viewing with local decoder fallbacks.", "zh-CN": "原生优先，并为 JPEG XL 与 HEIF 提供本地解码回退。" }, { en: "The probe tests browser decoding first, then the complete viewer loads only the decoder required by the selected image.", "zh-CN": "probe 优先测试浏览器解码；完整查看器随后只加载所选图片需要的解码器。" }, { en: ["Native decoding is preferred when it is available.", "JPEG XL or HEIF WebAssembly is loaded after plugin selection."], "zh-CN": ["可用时优先采用原生解码。", "JPEG XL 或 HEIF WebAssembly 只在插件选中后加载。"] }, { en: ["Large images remain bounded by browser memory.", "Advanced metadata is not a complete format inspector."], "zh-CN": ["大图片仍受浏览器内存限制。", "高级元数据展示不是完整格式检查器。"] }, [upstream("jxl-oxide-wasm", "0.12.6", "https://github.com/tirr-c/jxl-oxide", "MIT OR Apache-2.0", "JPEG XL decoding fallback.", "JPEG XL 解码回退。")]),
  plugin("camera-raw", { en: "How Anyfile's Camera RAW Viewer Works", "zh-CN": "Anyfile 相机 RAW 查看器如何工作" }, { en: "Metadata, embedded preview and basic RAW development on the device.", "zh-CN": "在设备端读取元数据、内嵌预览并进行基础 RAW 显影。" }, { en: "The viewer extracts the best embedded preview it can find and can invoke the isolated LibRaw-Wasm runtime for a basic developed image.", "zh-CN": "查看器会提取可用的最佳内嵌预览，并可调用隔离的 LibRaw-Wasm 运行时生成基础显影图。" }, { en: ["A lightweight probe validates known RAW containers.", "The threaded decoder is loaded only on the isolated /view route."], "zh-CN": ["轻量 probe 校验已知 RAW 容器。", "多线程解码器只在隔离的 /view 路由加载。"] }, { en: ["Results are representative, not a professional color workflow.", "Camera and compression variants can reduce support to metadata."], "zh-CN": ["结果只具代表性，不能替代专业色彩工作流。", "相机与压缩变体可能使支持降低到元数据级。"] }, [upstream("libraw-wasm", "1.6.0", "https://github.com/ybouane/LibRaw-Wasm", "ISC; bundled LibRaw is CDDL-1.0 OR LGPL-2.1", "RAW metadata extraction, thumbnails and basic development.", "RAW 元数据提取、缩略图与基础显影。")]),
  plugin("general-raster", { en: "How Anyfile's TIFF and General Raster Viewer Works", "zh-CN": "Anyfile TIFF 与通用栅格查看器如何工作" }, { en: "Local decoding for TIFF, TGA and Netpbm imagery.", "zh-CN": "在本地解码 TIFF、TGA 与 Netpbm 图片。" }, { en: "This viewer parses raster headers and decodes supported strips, tiles, pages or pixel runs into the shared image viewport.", "zh-CN": "该查看器解析栅格文件头，并把受支持的条带、分块、页面或像素游程解码到共享图片视口。" }, { en: ["Small format-specific probes identify decodable variants.", "TIFF decoding uses GeoTIFF while TGA and Netpbm use dedicated parsers."], "zh-CN": ["小型格式专用 probe 识别可解码变体。", "TIFF 使用 GeoTIFF 解码，TGA 与 Netpbm 使用专用解析器。"] }, { en: ["Unknown TIFF compression can leave pixels unavailable.", "Very large rasters are constrained by browser resources."], "zh-CN": ["未知 TIFF 压缩方式可能无法得到像素。", "超大栅格受浏览器资源限制。"] }, [upstream("GeoTIFF.js", "3.0.5", "https://github.com/geotiffjs/geotiff.js", "MIT", "TIFF directory, tile and strip decoding.", "TIFF 目录、分块与条带解码。")]),
  plugin("safe-svg", { en: "How Anyfile's Safe SVG Viewer Works", "zh-CN": "Anyfile 安全 SVG 查看器如何工作" }, { en: "Sanitized, isolated rendering for local SVG graphics.", "zh-CN": "为本地 SVG 图形提供清理后隔离渲染。" }, { en: "The plugin parses SVG as XML, removes active or unsafe constructs, and renders the sanitized result in a sandboxed frame.", "zh-CN": "插件把 SVG 解析为 XML，移除活动或不安全结构，并在沙箱 frame 中渲染清理结果。" }, { en: ["The probe verifies SVG structure without rendering it.", "Sanitization precedes isolated visual rendering."], "zh-CN": ["probe 在不渲染的情况下验证 SVG 结构。", "先完成清理，再进行隔离视觉渲染。"] }, { en: ["Scripts and active external resources are deliberately removed.", "Unavailable fonts can affect layout."], "zh-CN": ["脚本与活动外部资源会被有意移除。", "字体缺失可能影响版式。"] }),
  plugin("pdfjs-pdf", { en: "How Anyfile's PDF.js Viewer Works", "zh-CN": "Anyfile PDF.js 查看器如何工作" }, { en: "On-demand local PDF page rendering with Mozilla PDF.js.", "zh-CN": "使用 Mozilla PDF.js 按需在本地渲染 PDF 页面。" }, { en: "The viewer gives PDF.js an object URL for the selected file and renders visible pages into the browser without a server upload.", "zh-CN": "查看器通过对象 URL 把所选文件交给 PDF.js，并在浏览器中渲染可见页面，无需上传服务器。" }, { en: ["A signature probe verifies PDF candidates.", "PDF.js parses the document and renders pages on demand."], "zh-CN": ["签名 probe 校验 PDF 候选文件。", "PDF.js 解析文档并按需渲染页面。"] }, { en: ["Editing, annotations and form saving are unavailable.", "The selectable text layer is not enabled."], "zh-CN": ["不提供编辑、批注与表单保存。", "未启用可选择文本层。"] }, [upstream("Mozilla PDF.js", "6.2.108", "https://github.com/mozilla/pdf.js", "Apache-2.0", "PDF parsing and page rendering.", "PDF 解析与页面渲染。")]),
  plugin("word-document", { en: "How Anyfile's Word Viewer Works", "zh-CN": "Anyfile Word 查看器如何工作" }, { en: "Read-only browser reconstruction of DOCX documents.", "zh-CN": "在浏览器中只读重建 DOCX 文档。" }, { en: "The plugin validates the Open XML package and uses docx-preview to reconstruct supported document content and styles.", "zh-CN": "插件校验 Open XML 软件包，并使用 docx-preview 重建受支持的文档内容与样式。" }, { en: ["The package is checked before the complete renderer loads.", "DOCX XML, relationships and media are rendered into isolated DOM."], "zh-CN": ["完整渲染器加载前会先检查软件包。", "DOCX XML、关系与媒体被渲染到隔离 DOM。"] }, { en: ["Complex Word pagination and fields can differ.", "Editing, macros and tracked-change workflows are unavailable."], "zh-CN": ["复杂 Word 分页与字段可能有差异。", "不提供编辑、宏与修订工作流。"] }, [upstream("docx-preview", "0.4.0", "https://github.com/VolodymyrBaydalka/docxjs", "MIT", "DOCX parsing and browser rendering.", "DOCX 解析与浏览器渲染。")]),
  plugin("excel-workbook", { en: "How Anyfile's Spreadsheet Viewer Works", "zh-CN": "Anyfile 电子表格查看器如何工作" }, { en: "Read-only workbook parsing and virtualized sheet browsing.", "zh-CN": "只读解析工作簿并虚拟化浏览工作表。" }, { en: "SheetJS parses supported spreadsheet files; Anyfile then presents cell values and common formatting in a bounded grid.", "zh-CN": "SheetJS 解析受支持的电子表格文件，Anyfile 再把单元格值与常见格式呈现在有界网格中。" }, { en: ["A format probe validates the workbook before loading SheetJS.", "The shared table UI renders selected sheets without writing changes."], "zh-CN": ["格式 probe 在加载 SheetJS 前校验工作簿。", "共享表格 UI 渲染所选工作表且不写回修改。"] }, { en: ["It is not a complete formula or chart engine.", "Macros and external connections never execute."], "zh-CN": ["它不是完整公式或图表引擎。", "绝不执行宏和外部连接。"] }, [upstream("SheetJS", "0.20.3", "https://git.sheetjs.com/sheetjs/sheetjs", "Apache-2.0", "Spreadsheet container and worksheet parsing.", "电子表格容器与工作表解析。")]),
  plugin("powerpoint-presentation", { en: "How Anyfile's PowerPoint Viewer Works", "zh-CN": "Anyfile PowerPoint 查看器如何工作" }, { en: "Static, read-only rendering for PPTX slide decks.", "zh-CN": "为 PPTX 幻灯片提供静态只读渲染。" }, { en: "The plugin validates the PPTX archive and asks the renderer to build supported slide elements in the browser.", "zh-CN": "插件校验 PPTX 归档，并让渲染器在浏览器中构建受支持的幻灯片元素。" }, { en: ["ZIP safety limits are applied before rendering.", "Slides are reconstructed as read-only browser content."], "zh-CN": ["渲染前会应用 ZIP 安全限制。", "幻灯片被重建为只读浏览器内容。"] }, { en: ["Animations and transitions are not reproduced.", "Advanced effects can differ from PowerPoint."], "zh-CN": ["不复现动画与切换效果。", "高级效果可能与 PowerPoint 不同。"] }, [upstream("@aiden0z/pptx-renderer", "1.2.4", "https://www.npmjs.com/package/@aiden0z/pptx-renderer", "MIT", "PPTX parsing and DOM rendering.", "PPTX 解析与 DOM 渲染。")]),
  plugin("http-archive", { en: "How Anyfile's HTTP Archive Viewer Works", "zh-CN": "Anyfile HTTP Archive 查看器如何工作" }, { en: "Structured, non-replaying inspection of HAR network captures.", "zh-CN": "结构化检查 HAR 网络捕获，且不重放请求。" }, { en: "The custom parser validates HAR JSON and derives request, header, size and timing views entirely from the saved file.", "zh-CN": "自研解析器校验 HAR JSON，并完全从保存文件派生请求、标头、大小与耗时视图。" }, { en: ["The archive is parsed without contacting recorded hosts.", "A request-oriented UI exposes captured metadata."], "zh-CN": ["解析归档时不会联系其中记录的主机。", "面向请求的 UI 展示捕获元数据。"] }, { en: ["It does not replay traffic.", "Sensitive captured values remain visible in the local UI."], "zh-CN": ["不会重放网络流量。", "捕获的敏感值仍会显示在本地 UI 中。"] }),
  plugin("ace-code-text", { en: "How Anyfile's Code and Text Viewer Works", "zh-CN": "Anyfile 代码与文本查看器如何工作" }, { en: "Read-only syntax-aware viewing for source and text files.", "zh-CN": "为源码与文本文件提供语法感知只读查看。" }, { en: "The plugin selects an Ace mode from the file name and opens content in a read-only editor surface without executing it.", "zh-CN": "插件根据文件名选择 Ace mode，并在只读编辑器界面打开内容且不执行。" }, { en: ["Only the selected syntax mode is dynamically loaded.", "Ace provides navigation, selection and highlighting in read-only mode."], "zh-CN": ["只动态加载所选语法模式。", "Ace 以只读模式提供导航、选择与高亮。"] }, { en: ["Ace workers are disabled, so live validation is unavailable.", "Binary or incorrectly encoded text may not display meaningfully."], "zh-CN": ["Ace Worker 已禁用，因此不提供实时校验。", "二进制或编码错误文本可能无法有意义地显示。"] }, [upstream("Ace", "1.44.0", "https://github.com/ajaxorg/ace", "BSD-3-Clause", "Read-only editor surface and syntax modes.", "只读编辑器界面与语法模式。")]),
  plugin("sqlite-database", { en: "How Anyfile's SQLite Viewer Works", "zh-CN": "Anyfile SQLite 查看器如何工作" }, { en: "Read-only schema and table browsing through SQLite WebAssembly.", "zh-CN": "通过 SQLite WebAssembly 只读浏览 schema 与数据表。" }, { en: "sql.js opens a copy of the selected database in browser memory; the viewer enumerates tables and pages query results without saving changes.", "zh-CN": "sql.js 在浏览器内存中打开所选数据库副本；查看器枚举数据表并分页查询结果，不保存修改。" }, { en: ["A signature probe rejects non-SQLite files.", "The WASM engine and table UI load only after selection."], "zh-CN": ["签名 probe 拒绝非 SQLite 文件。", "WASM 引擎与表格 UI 只在选中后加载。"] }, { en: ["Database size is bounded by browser memory.", "Encrypted databases and arbitrary user SQL are unsupported."], "zh-CN": ["数据库大小受浏览器内存限制。", "不支持加密数据库与任意用户 SQL。"] }, [upstream("sql.js", "1.14.2", "https://github.com/sql-js/sql.js", "MIT", "SQLite engine compiled to WebAssembly.", "编译为 WebAssembly 的 SQLite 引擎。")]),
  plugin("dev-array-viewer", { en: "How Anyfile's NumPy Array Viewer Works", "zh-CN": "Anyfile NumPy 数组查看器如何工作" }, { en: "Bounded NPY and NPZ structure and value inspection.", "zh-CN": "有界检查 NPY 与 NPZ 结构和数值。" }, { en: "The custom parser reads NumPy headers and safe primitive layouts, then exposes array metadata and paged values without Python.", "zh-CN": "自研解析器读取 NumPy 文件头与安全基础类型布局，无需 Python 即可展示数组元数据和分页数值。" }, { en: ["NPZ entries are indexed before an array is selected.", "Binary values are decoded in bounded pages."], "zh-CN": ["选择数组前先索引 NPZ 条目。", "二进制值以有界分页解码。"] }, { en: ["Object arrays are intentionally rejected.", "High-dimensional values use an inspection-oriented flattened view."], "zh-CN": ["会有意拒绝对象数组。", "高维数值使用面向检查的展平视图。"] }),
  plugin("dev-wasm-viewer", { en: "How Anyfile's WebAssembly Inspector Works", "zh-CN": "Anyfile WebAssembly 检查器如何工作" }, { en: "Structural module inspection without WebAssembly execution.", "zh-CN": "不执行 WebAssembly 的模块结构检查。" }, { en: "A custom binary reader validates WASM sections and builds summaries for types, imports, exports, memory and code bodies.", "zh-CN": "自研二进制读取器校验 WASM 段，并为类型、导入导出、内存与代码体生成摘要。" }, { en: ["The magic and version are checked during probing.", "Sections are parsed incrementally into a navigable model."], "zh-CN": ["probe 会检查魔数与版本。", "各段被增量解析为可导航模型。"] }, { en: ["It does not decompile source code.", "The module is never instantiated, so runtime behavior is not shown."], "zh-CN": ["不会反编译源码。", "模块绝不实例化，因此不展示运行时行为。"] }),
  plugin("dev-source-map-viewer", { en: "How Anyfile's Source Map Viewer Works", "zh-CN": "Anyfile Source Map 查看器如何工作" }, { en: "ECMA-426 mapping, source and coverage inspection.", "zh-CN": "检查 ECMA-426 映射、源码与覆盖。" }, { en: "The parser validates source-map JSON, decodes VLQ mappings and exposes sources, names, coverage and position lookup.", "zh-CN": "解析器校验 Source Map JSON、解码 VLQ 映射，并展示 sources、names、覆盖与位置查询。" }, { en: ["Mappings decode locally without loading generated code.", "Embedded sources are shown only when present in the file."], "zh-CN": ["映射在本地解码，不加载生成代码。", "只有文件中存在时才展示内嵌源码。"] }, { en: ["Missing original sources cannot be fetched or reconstructed.", "Nonstandard malformed maps are rejected."], "zh-CN": ["无法获取或重建缺失的原始源码。", "非标准损坏映射会被拒绝。"] }),
  plugin("duckdb-data", { en: "How Anyfile's DuckDB Data Viewer Works", "zh-CN": "Anyfile DuckDB 数据查看器如何工作" }, { en: "Paged local querying for structured files and DuckDB databases.", "zh-CN": "为结构化文件与 DuckDB 数据库提供本地分页查询。" }, { en: "The selected file is registered with DuckDB-Wasm, queried read-only, and returned as Arrow batches for a virtualized table UI.", "zh-CN": "所选文件注册到 DuckDB-Wasm，以只读方式查询，再以 Arrow 批次返回虚拟化表格 UI。" }, { en: ["A small format probe runs before the heavy runtime loads.", "DuckDB-Wasm and its Worker initialize only after viewer selection."], "zh-CN": ["重型运行时加载前会运行小型格式 probe。", "DuckDB-Wasm 与 Worker 只在查看器选中后初始化。"] }, { en: ["Cold start downloads or loads a multi-megabyte WASM bundle.", "Nested data flattening and supported compression follow DuckDB."], "zh-CN": ["冷启动需要下载或加载数 MB WASM bundle。", "嵌套数据展平与压缩支持取决于 DuckDB。"] }, [upstream("DuckDB-Wasm", "1.32.0", "https://github.com/duckdb/duckdb-wasm", "MIT", "Read-only local query engine and format readers.", "只读本地查询引擎与格式读取器。"), upstream("Apache Arrow JS", "17.0.0", "https://github.com/apache/arrow-js", "Apache-2.0", "Columnar result batches exchanged with the table UI.", "与表格 UI 交换的列式结果批次。")]),
  plugin("archive-metadata-viewer", { en: "How Anyfile's Archive Metadata Viewer Works", "zh-CN": "Anyfile 归档元数据查看器如何工作" }, { en: "Bounded local listings for ZIP-derived and compressed archives.", "zh-CN": "有界列出 ZIP 派生与压缩归档内容。" }, { en: "The plugin identifies the container, applies safety limits and builds a directory listing without installing packages or executing archive entries.", "zh-CN": "插件识别容器、应用安全限制并生成目录列表，不安装软件包，也不执行归档条目。" }, { en: ["Container signatures and headers are checked first.", "Entry metadata is streamed or indexed under explicit limits."], "zh-CN": ["先检查容器签名与文件头。", "条目元数据在明确限制下流式读取或索引。"] }, { en: ["It is a metadata browser, not a universal extractor.", "Encrypted or extreme archives may be rejected."], "zh-CN": ["它是元数据浏览器，不是通用解压工具。", "加密或极端归档可能被拒绝。"] }, [upstream("zip.js", "2.8.60", "https://github.com/gildas-lormeau/zip.js", "BSD-3-Clause", "ZIP and ZIP-derived directory parsing.", "ZIP 与 ZIP 派生目录解析。")]),
  plugin("hex-viewer", { en: "How Anyfile's Hex Fallback Viewer Works", "zh-CN": "Anyfile 十六进制兜底查看器如何工作" }, { en: "Bounded byte inspection when no richer viewer applies.", "zh-CN": "没有更丰富查看器时提供有界字节检查。" }, { en: "The fallback viewer reads small slices of any selected file and shows hexadecimal offsets, bytes and text equivalents.", "zh-CN": "兜底查看器读取任意所选文件的小片段，并显示十六进制偏移、字节与文本对应值。" }, { en: ["It remains the lowest-priority wildcard registration.", "File slices are read on demand instead of loading the full file."], "zh-CN": ["它始终是最低优先级通配注册项。", "按需读取文件切片，而不是加载完整文件。"] }, { en: ["Bytes do not amount to format-aware viewing.", "Text columns are only a byte interpretation, not encoding detection."], "zh-CN": ["字节展示不等于格式感知查看。", "文本列只是字节解释，不进行编码检测。"] }),
];
