import { calibreAlternative, archiveToolAlternative } from "./archive-shared";
import { defineFormat } from "./define-format";
export const mobiFormats = ["mobi", "azw", "azw3", "prc", "pdb"].map(extension => defineFormat(extension, "documents", 3,
  { name: `${extension.toUpperCase()} ebook`, title: `Read ${extension.toUpperCase()} Books Online`, description: `${extension.toUpperCase()}: Read unencrypted MOBI, KF8 and PalmDOC books locally.`, introduction: `${extension.toUpperCase()}: Open supported Palm database books without uploading them. Read the reconstructed text, contents and common images in your browser.`, canShow: ["PalmDOC, MOBI7 and KF8; the KF8 part of joint books", "UTF-8 and Windows-1252 text, metadata, contents and common images", "Adjustable text, local chapter links and basic CSS"], limitations: ["Only BOOK/MOBI and TEXt/REAd databases; no arbitrary PDB, DRM, KFX, dictionaries or Print Replica", "64 MiB file, 32 MiB expanded text, 2 MiB per chapter; complex layout is simplified"], faq: [{ question: `${extension.toUpperCase()}: Can it remove Kindle DRM?`, answer: "No. Protected books are detected and cannot be read." }] },
  { name: `${extension.toUpperCase()} 电子书`, title: `在线阅读 ${extension.toUpperCase()} 电子书`, description: `${extension.toUpperCase()}: 本地阅读无 DRM 的 MOBI、KF8 与 PalmDOC 图书。`, introduction: `${extension.toUpperCase()}: 无需上传，在浏览器中阅读受支持 Palm 数据库图书的正文、目录与常见图片。`, canShow: ["PalmDOC、MOBI7、KF8；联合图书选择 KF8 部分", "UTF-8、Windows-1252 正文、元数据、目录和常见图片", "排版设置、书内章节链接与基本 CSS"], limitations: ["仅 BOOK/MOBI、TEXt/REAd 数据库；不支持任意 PDB、DRM、KFX、词典或 Print Replica", "文件 64 MiB、展开正文 32 MiB、单章 2 MiB；复杂排版会简化"], faq: [{ question: `${extension.toUpperCase()}: 可以移除 Kindle DRM 吗？`, answer: "不能。识别到保护后会显示不支持状态。" }] },
  { possibleLevels: [3], verification: "verified" }, calibreAlternative));
export const comicArchiveFormats = ["cbr", "cb7", "cbt"].map(extension => defineFormat(extension, "documents", 4,
  { name: `${extension.toUpperCase()} comic`, title: `Read ${extension.toUpperCase()} Comics Online`, description: `${extension.toUpperCase()}: Read local comic archives with natural page order and manga controls.`, introduction: `${extension.toUpperCase()}: Browse comic images locally using single pages, spreads or continuous scrolling.`, canShow: ["CBR RAR4/RAR5, CB7 7z Copy/LZMA/LZMA2, CBT ordinary USTAR", "JPEG, PNG, GIF, WebP and static AVIF pages, natural sorting and ComicInfo", "Page jump, fit width/height, zoom, keyboard and RTL"], limitations: ["No encryption, split archives, links or special TAR entries", "Compressed comics: 64 MiB input, 128 MiB total expansion; sequential extraction before reading", "5,000 pages, 16 MiB and 8 million pixels per page; TAR input up to 2 GiB"], faq: [{ question: `${extension.toUpperCase()}: How does a solid archive work?`, answer: "It is extracted once within fixed limits; subsequent page jumps use local encoded images. Opening does not decode all images." }] },
  { name: `${extension.toUpperCase()} 漫画`, title: `在线阅读 ${extension.toUpperCase()} 漫画`, description: `${extension.toUpperCase()}: 本地阅读漫画归档，支持自然页序、双页与漫画方向。`, introduction: `${extension.toUpperCase()}: 在浏览器中按单页、双页或连续滚动阅读本地漫画图片。`, canShow: ["CBR RAR4/RAR5、CB7 7z Copy/LZMA/LZMA2、CBT 普通 USTAR", "JPEG、PNG、GIF、WebP、静态 AVIF，自然排序与 ComicInfo", "跳页、适宽/适高、缩放、键盘与 RTL"], limitations: ["不支持加密、分卷、链接与 TAR 特殊条目", "压缩漫画输入 64 MiB，累计展开 128 MiB；阅读前顺序解压一次", "最多 5,000 页，每页 16 MiB、800 万像素；TAR 输入最多 2 GiB"], faq: [{ question: `${extension.toUpperCase()}: 固实归档如何读取？`, answer: "在固定预算内顺序解压一次，之后跳页读取本地编码图片，打开时不解码全部图片。" }] },
  { possibleLevels: extension === "cb7" ? [4] : [2, 4], verification: "verified" }, archiveToolAlternative));
